default: &default
  # If app should only be using a specific collection,
  # append "/collection/(collection_name)" to path
  api_path: https://cdrhdev1.unl.edu/api/v1
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

test:
  <<: *default

development:
  <<: *default
  api_path: https://cdrhdev1.unl.edu/api/v1
  # data endpoint, used for geojson retrieval from media server
  data_path: https://cdrhdev1.unl.edu/media/data/family_letters

production:
  <<: *default
  api_path: https://cdrhapi.unl.edu/v1
  data_path: https://cdrhmedia.unl.edu/data/family_letters
