default: &default
  # If app should only be using a specific collection,
  # append "/collection/(collection_name)" to path
  api_path: https://servername.unl.edu/api-v2
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

test:
  <<: *default

development:
  <<: *default
  api_path: https://servername.unl.edu/api-v2
  # data endpoint, used for geojson retrieval from media server
  data_path: https://servername.unl.edu/media/data/family_letters

production:
  <<: *default
  api_path: https://servername.unl.edu/api-v2
  data_path: https://cdrhmedia.unl.edu/data/family_letters
