default: &default

  app_options:
    version: 0.1.0
    # defaults to "en" (english) if no default language set
    language_default: es
    # pipe delineated codes for all languages, e.g. "en|es|cz"
    languages: es|en
    # iiif thumbnail default size
    thumbnail_size: "!150,150"
    # iiif project directory
    media_server_dir: family_letters

  api_options:
    # example of default filter for all queries
    # f:
    #   - subcategory|Writings
    # sorting and response number
    sort:
      # typically use title as sort except that the title
      # field could be spanish or english, so changing default to date
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: count|desc
    # highlighting
    hl_fl: text_t_es,text_t_en
    hl_num: 5

  date_range:
    first:
      - 1600
      - 01
      - 01
    last:
      - 2100
      - 12
      - 31

  facets:
    en:
      subcategory:
        label: Category
        flags:
          - search_filter
      date.year:
        label: Year
        flags:
          - search_filter
      person.name:
        label: People
        flags:
          - search_filter
      language:
        label: Primary Language
        flags:
          - search_filter
      creator.name:
        label: Author
        flags:
          - search_filter
      format:
        label: Format
        flags:
          - search_filter
      places:
        label: Location
        flags:
          - search_filter
    es:
      subcategory:
        label: Categoría
        flags:
          - search_filter
          - translate
      date.year:
        label: Año
        flags:
          - search_filter
      person.name:
        label: Persona
        flags:
          - search_filter
      language:
        label: Idioma Original
        flags:
          - search_filter
      creator.name:
        label: Autor
        flags:
          - search_filter
      format:
        label: Formato
        flags:
          - search_filter
          - translate
      places:
        label: Localidad
        flags:
          - search_filter

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
