default: &default

  app_options:
    version: 0.1.0
    # defaults to "en" (english) if no default language set
    language_default: es
    # pipe delineated values (es|de) for all non-default languages
    languages: en
    # iiif thumbnail default size
    thumbnail_size: "!150,150"
    # iiif project directory
    media_server_dir: family_letters

  api_options:
    # example of default filter for all queries
    # f:
    #   - subcategory|Writings
    # sorting and response number
    sort:
      - title|asc
    rows: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_fl: text_t_es,text_t_en
    hl_num: 5

  date_range:
    first:
      - 1600
      - 01
      - 01
    last:
      - 2100
      - 12
      - 31

  facets:
    en:
      category:
        label: Category
        flags:
          - search_filter
      date.year:
        label: Year
        flags:
          - search_filter
      person.name:
        label: People
        flags:
          - search_filter
      languages:
        label: Language
        flags:
          - search_filter
      subcategory:
        label: Subcategory
        flags:
          - search_filter
      creator.name:
        label: Creator
        flags:
          - search_filter
      format:
        label: Format
        flags:
          - search_filter
      places:
        label: Places
        flags:
          - search_filter
    es:
      category:
        label: Categoría
        flags:
          - search_filter
          - translate
      date.year:
        label: Año
        flags:
          - search_filter
      person.name:
        label: Gente
        flags:
          - search_filter
      languages:
        label: Idioma
        flags:
          - search_filter
      subcategory:
        label: Subcategoría
        flags:
          - search_filter
          - translate
      creator.name:
        label: Autor
        flags:
          - search_filter
      format:
        label: Formato
        flags:
          - search_filter
          - translate
      places:
        label: Sitio
        flags:
          - search_filter

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
