default: &default

  app_options:
    version: 0.1.0
    # defaults to "en" (english) if no default language set
    language_default: es
    # defaults to "en" if nothing passed in, pipe delineated values (en|es|de)
    languages: en|es

  api_options:
    # example of default filter for all queries
    # f:
    #   - subcategory|Writings
    # sorting and response number
    sort:
      - title|asc
    rows: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_fl: text
    hl_num: 5

  date_range:
    first:
      - 1600
      - 01
      - 01
    last:
      - 2100
      - 12
      - 31

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
